Repository jesh-hub/account-book-slim, pull requests merged in 2022-08, with the labels that each got.

#114 내역 등록 기능 추가하기
  back-end/serverless.yml
  back-end/util/error_handler.go
  front-end/src/App.js
  front-end/src/App.scss
  front-end/src/pages/GroupListView.jsx
  front-end/src/pages/GroupListView.scss
  front-end/src/pages/MainApp.jsx
  front-end/src/pages/MainApp.scss
  front-end/src/pages/PaymentRegisterView.jsx
  front-end/src/pages/PaymentRegisterView.scss
Labels: frontend, feature

#115 feat: 내역 확인 버튼 클릭하면 거래 내역 보여주기
  front-end/src/App.js
  front-end/src/_bak/OldApp.js
  front-end/src/_bak/OldApp.scss
  front-end/src/_bak/OldApp.test.js
  front-end/src/components/PaymentListView.js
  front-end/src/components/PaymentListView.scss
  front-end/src/components/SummaryBySign.js
  front-end/src/pages/GroupListView.jsx
  front-end/src/pages/PaymentListView.jsx
  front-end/src/pages/PaymentListView.scss
Labels: frontend, feature

#120 fix: 결제내역 업데이트
  back-end/service/payment_s.go
Labels: bug, backend

#121 등록한 거래 내역 추가할 수 있게 하기
  front-end/src/common/Common.scss
  front-end/src/pages/PaymentListView.jsx
  front-end/src/pages/PaymentListView.scss
  front-end/src/pages/PaymentRegisterView.jsx
Labels: bug, frontend, feature

#123 refactor: restful한 API 적용
  .github/workflows/backend-cicd.yml
  back-end/Makefile
  back-end/controller/group_c.go
  back-end/controller/payment_c.go
  back-end/controller/payment_method_c.go
  back-end/controller/user_c.go
  back-end/go.mod
  back-end/go.sum
  back-end/main.go
  back-end/model/group.go
  back-end/model/payment.go
  back-end/model/payment_method.go
  back-end/model/user.go
  back-end/pkg/slack/history.go
  back-end/pkg/slack/payment.go
  back-end/pkg/slack/slack.go
  back-end/pkg/slack/slack_test.go
  back-end/router/router.go
  back-end/service/group_s.go
  back-end/service/payment_method_s.go
  back-end/service/payment_s.go
  back-end/service/user_s.go
  front-end/src/pages/GroupListView.jsx
  front-end/src/pages/PaymentListView.jsx
  front-end/src/pages/PaymentRegisterView.jsx
Labels: enhancement, backend, frontend, refactor

#126 feat: group 삭제 API
  back-end/controller/group_c.go
  back-end/router/router.go
  back-end/service/group_s.go
Labels: backend, feature

#128 그룹 추가 api 수정 결제수단 처리
  back-end/controller/group_c.go
  back-end/controller/payment_method_c.go
  back-end/go.mod
  back-end/go.sum
  back-end/model/group.go
  back-end/model/payment_method.go
  back-end/service/group_s.go
  back-end/service/payment_method_s.go
Labels: enhancement, backend

#129 feat: 그룹 추가할 수 있게 하기
  front-end/src/App.js
  front-end/src/common/useRouterNavigateWith.js
  front-end/src/pages/GroupListView.jsx
  front-end/src/pages/GroupRegisterView.jsx
  front-end/src/pages/GroupRegisterView.scss
  front-end/src/pages/MainApp.jsx
Labels: frontend, feature

#130 Refactor 코드정리
  back-end/cmd/app.go
  back-end/controller/user_c.go
  back-end/database/database.go
  back-end/main.go
  back-end/middleware/middleware.go
  back-end/model/payment.go
  back-end/model/payment_method.go
  back-end/model/user.go
  back-end/router/api/group_c.go
  back-end/router/api/payment_c.go
  back-end/router/api/payment_method_c.go
  back-end/router/api/user_c.go
  back-end/router/router.go
  back-end/service/group_s.go
  back-end/service/payment_method_s.go
  back-end/service/payment_s.go
  back-end/service/user_s.go
  back-end/tests/payment_test.go
  back-end/tests/user_test.go
  back-end/util/converter.go
  back-end/util/error_handler.go
Labels: backend, refactor

#134 월별 지출 수입 합계 API 추가
  .github/workflows/backend-cicd.yml
  back-end/go.mod
  back-end/go.sum
  back-end/model/group.go
  back-end/model/payment.go
  back-end/router/api/payment_c.go
  back-end/router/router.go
  back-end/service/group_s.go
  back-end/service/payment_method_s.go
  back-end/service/payment_s.go
Labels: enhancement, backend
