Repository jesh-hub/account-book-slim, pull requests merged in 2022-05, with the labels that each got.

#42 feat: backend cicd 구성
  .github/workflows/backend-cicd.yml
  .github/workflows/codeql.yml
  .github/workflows/frontend-cicd.yml
  back-end/Makefile
Labels: DevOps, AWS

#43 fix: serverless/github-action@v3가 sub-directory를 지원하지 않는 문제
  .github/workflows/backend-cicd.yml
Labels: bug, DevOps

#44 fix: 시간 locale(utc,kst) 때문에 데이터가 누락되는 문제
  back-end/pkg/slack/history.go
Labels: bug, backend

#47 fix: Slack API 요청할 때와 가져온 채팅을 필터링할 때 타임존 다르게 설정
  back-end/pkg/slack/history.go
  back-end/pkg/slack/slack_test.go
Labels: bug

#50 enhance: 슬랙 채팅의 날짜 금액 규칙 호환성 제공, 성능 향상
  back-end/payments/main.go
  back-end/pkg/slack/history.go
  back-end/pkg/slack/slack_test.go
Labels: enhancement, backend

#51 49 modify 헤더를 고정하는 방식 수정하기
  front-end/public/index.html
  front-end/src/App.css
  front-end/src/components/PaymentListView.css
Labels: frontend

#54 refactor: Api 요청을 하는 custom hook 만들기
  front-end/src/App.js
  front-end/src/common/useRequest.js
Labels: frontend

#62 fix: api response에 대한 에러 처리하기
  front-end/src/App.css
  front-end/src/App.js
  front-end/src/common/ErrorContext.js
  front-end/src/common/useRequest.js
  front-end/src/components/ErrorLogger.js
Labels: frontend

#65 64 절대 경로로 import 할 수 있게 수정하기
  front-end/config-overrides.js
  front-end/package.json
  front-end/src/App.js
  front-end/src/App.test.js
  front-end/src/common/ProcessingSpinner.js
  front-end/src/common/useRequest.js
  front-end/src/components/ErrorLogger.js
  front-end/src/components/PaymentListView.js
  front-end/src/index.js
  front-end/webpack.config.js
  front-end/yarn.lock
Labels: frontend

#67 security: css-select
  front-end/yarn.lock
Labels: dependencies

#69 security: nth-check
  front-end/yarn.lock
Labels: dependencies
