Repository jesh-hub/account-book-slim, pull requests merged in 2022-06, with the labels that each got.

#74 security: dependencies upgrade yaml (CVE-2022-28948)
  back-end/go.mod
  back-end/go.sum
Labels: backend, dependencies

#76 ci: serverless 배포 효율화
  .github/workflows/backend-cicd.yml
  back-end/Makefile
Labels: backend, DevOps

#77 ci: upgrade all go module
  back-end/go.mod
  back-end/go.sum
Labels: backend, dependencies

#81 78: add react router
  front-end/package.json
  front-end/src/index.js
  front-end/yarn.lock
Labels: frontend

#83 82 feat mongo 연결하기
  .github/workflows/backend-cicd.yml
  back-end/Makefile
  back-end/go.mod
  back-end/go.sum
  back-end/pkg/mongo/database.go
  back-end/pkg/mongo/database_test.go
  back-end/serverless.yml
  back-end/user/signup/main.go
Labels: backend, AWS

#86 85: feat group payment method api 구현
  back-end/internal/abs/group.go
  back-end/internal/abs/group_test.go
  back-end/internal/abs/payment.go
  back-end/internal/abs/payment_test.go
  back-end/internal/abs/router.go
  back-end/internal/abs/user.go
  back-end/internal/abs/user_test.go
Labels: backend
